# This is a basic workflow to help you get started with Actions

name: RPI-CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel, release/v3.0.0 ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'
env:
  RPI_TOOLCHAIN_DIR: /tmp/rpi-toolchain
  DICTIONARY_PATH: build-artifacts/raspberrypi/RPI/dict/RPITopologyAppDictionary.xml
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  RPI:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout F´ Repository"
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: true
    - uses: ./.github/actions/setup
    - name: Setup RPI Toolchain
      uses: fprime-community/setup-rpi-sysroot@main
    - name: F prime CI step
      run: ./ci/tests/RPI.bash
    - name: Copy Tests
      run: mkdir -p artifact/RPI; cp -rp RPI/test RPI/build-artifacts artifact/RPI; cp -rp ci artifact
    # Build Artifacts
    - name: 'RPI Build Output'
      uses: actions/upload-artifact@v3
      with:
        name: rpi-build
        path: artifact
        retention-days: 5
    # Archive the outputs
    - name: 'Archive Logs'
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: rpi-logs
        path: ci-logs.tar.gz
        retention-days: 5

  RPI-Integration:
    runs-on: self-hosted
    needs: RPI
    steps:
    - name: RPI Build Download
      uses: actions/download-artifact@v3
      with:
        name: rpi-build
    - name: RPI Integration Tests
      run: chmod +x RPI/build-artifacts/raspberrypi/RPI/bin/RPI; /bin/bash ci/tests/RPI-Ints.bash
    # Archive the outputs
    - name: 'Archive Logs'
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: pi-int-logs
        path: ci-logs.tar.gz
        retention-days: 5
    # Clean-Up moved to post script to prevent collisions
