# Builds and runs UTs on https://github.com/fprime-community/fprime-workshop-led-blinker

name: "Tutorial: LedBlinker"

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/actions/spelling/**'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  get-branch:
    name: "Get target branch"
    uses: ./.github/workflows/reusable-get-pr-branch.yml
    with:
      target_repository: fprime-community/fprime-workshop-led-blinker

  run:
    needs: get-branch
    name: ""
    uses: ./.github/workflows/reusable-project-builder.yml
    with: 
      target_repository: fprime-community/fprime-workshop-led-blinker
      build_location: LedBlinker
      run_unit_tests: true
      target_ref: ${{ needs.get-branch.outputs.target-branch }}
