# This is a basic workflow to help you get started with Actions

name: tutorial-support

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the devel branch
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout latest GpsApp repo
        uses: actions/checkout@v2
        with:
          repository: fprime-community/gps-tutorial
          path: ./gps-tutorial

      # Checks-out latest version of the fprime repo
      - name: checkout latest fprime repo
        uses: actions/checkout@v2
        with:
          path: ./gps-tutorial/fprime

      # Build tutorial test
      - name: tutorial-test
        uses: ./gps-tutorial/fprime/.github/actions/tutorial/
        id: github-tutorial-action
